import { describe, expect, it } from 'vitest';
import { classify, textSimilarity, type AccountHistory, type PRInput } from '../src/classify';

const noHistory: AccountHistory = { priorDisclosures: [] };

describe('textSimilarity', () => {
  it('is 1.0 for identical text', () => {
    expect(textSimilarity('Used Claude to fix a typo', 'Used Claude to fix a typo')).toBe(1);
  });

  it('is low for genuinely different descriptions', () => {
    const sim = textSimilarity(
      'Used Claude to fix a typo in the changelog',
      'Refactored the sidebar store to use signals instead of context',
    );
    expect(sim).toBeLessThan(0.2);
  });
});

describe('classify -- baseline cases (no disclosure)', () => {
  it('grades a clean human PR as human', () => {
    const pr: PRInput = {
      behavioralAutomationScore: 0.1,
      disclosureText: null,
      claimedScope: null,
      diffStats: { filesChanged: 2, linesChanged: 30 },
    };
    expect(classify(pr, noHistory).classification).toBe('human');
  });

  it('grades an undisclosed, clearly automated PR as automated', () => {
    const pr: PRInput = {
      behavioralAutomationScore: 0.9,
      disclosureText: null,
      claimedScope: null,
      diffStats: { filesChanged: 5, linesChanged: 400 },
    };
    expect(classify(pr, noHistory).classification).toBe('automated');
  });
});

describe('classify -- fixes the two real reported failure directions', () => {
  it('storybook#36085 pattern: disclosed + human-reviewed + high behavioral score no longer grades "automated"', () => {
    const pr: PRInput = {
      behavioralAutomationScore: 0.85, // looked automated behaviorally
      disclosureText: 'Used Claude Code to draft this fix, then reviewed and tested it manually before submitting.',
      claimedScope: 'moderate',
      diffStats: { filesChanged: 3, linesChanged: 120 },
    };
    const result = classify(pr, noHistory);
    expect(result.classification).toBe('disclosed-assisted');
    expect(result.classification).not.toBe('automated');
  });

  it('storybook#36145/#36146 pattern: disclosed + human-looking behavior is no longer silently absorbed into plain "human"', () => {
    const pr: PRInput = {
      behavioralAutomationScore: 0.15, // looked entirely human behaviorally
      disclosureText: 'AI-assisted: used GitHub Copilot for the type refactor, wrote the tests myself.',
      claimedScope: 'moderate',
      diffStats: { filesChanged: 4, linesChanged: 90 },
    };
    const result = classify(pr, noHistory);
    expect(result.classification).toBe('disclosed-assisted');
    expect(result.classification).not.toBe('human');
  });
});

describe('classify -- anti-gaming: the exact attack the brief warns about', () => {
  it('a first-time disclosure gets the benefit of the doubt', () => {
    const pr: PRInput = {
      behavioralAutomationScore: 0.95,
      disclosureText: 'This PR was generated by an AI agent as part of automated maintenance.',
      claimedScope: 'minor',
      diffStats: { filesChanged: 1, linesChanged: 5 },
    };
    expect(classify(pr, noHistory).classification).toBe('disclosed-assisted');
  });

  it('pasting the SAME boilerplate disclosure across many PRs from a fully-automated account gets flagged, not laundered through', () => {
    const boilerplate = 'This PR was generated by an AI agent as part of automated maintenance.';
    const history: AccountHistory = { priorDisclosures: [] };
    const highlyAutomatedPr = (): PRInput => ({
      behavioralAutomationScore: 0.97,
      disclosureText: boilerplate,
      claimedScope: 'minor',
      diffStats: { filesChanged: 1, linesChanged: 5 },
    });

    // First two occurrences: indistinguishable from a legitimate account
    // that happens to phrase disclosures consistently -- correctly not
    // flagged yet, since flagging on a single instance would also
    // penalize an honest account with a consistent personal disclosure
    // style.
    const first = classify(highlyAutomatedPr(), history);
    expect(first.classification).toBe('disclosed-assisted');
    history.priorDisclosures.unshift(boilerplate);

    const second = classify(highlyAutomatedPr(), history);
    expect(second.classification).toBe('disclosed-assisted');
    history.priorDisclosures.unshift(boilerplate);

    // Third near-identical disclosure from a fully-automated account trips
    // the boilerplate trip-wire -- this is the case the brief specifically
    // named as the failure mode a naive implementation would miss.
    const third = classify(highlyAutomatedPr(), history);
    expect(third.classification).toBe('flagged-for-review');
    expect(third.reasons.join(' ')).toContain('boilerplate');
  });

  it('a disclosure that understates the actual size of the change gets flagged', () => {
    const pr: PRInput = {
      behavioralAutomationScore: 0.8,
      disclosureText: 'Minor AI-assisted typo fix.',
      claimedScope: 'minor',
      diffStats: { filesChanged: 22, linesChanged: 640 }, // not a typo fix
    };
    const result = classify(pr, noHistory);
    expect(result.classification).toBe('flagged-for-review');
    expect(result.reasons.join(' ')).toContain('scope');
  });

  it('an honest account describing genuinely different changes each time never trips the boilerplate check', () => {
    const history: AccountHistory = {
      priorDisclosures: [
        'Used Claude to refactor the sidebar store to use signals.',
        'AI-assisted rewrite of the CSF parser for definePreview support.',
      ],
    };
    const pr: PRInput = {
      behavioralAutomationScore: 0.7,
      disclosureText: 'Used Copilot to help write the new addon registration API and its tests.',
      claimedScope: 'moderate',
      diffStats: { filesChanged: 6, linesChanged: 210 },
    };
    const result = classify(pr, history);
    expect(result.classification).toBe('disclosed-assisted');
  });
});
